easy_admin:
   site_name: 'Dev my shirts'
   design:
        brand_color: '#00A2A5'
        menu: 
            - { label: 'Les commandes' }
            - { entity: 'OrderLine', label: 'Commandes' , icon: '' }
            - { entity: 'Orders', label: 'Numéro de commandes', icon: '', default: true }
            - { entity: 'Rate', label: 'Remise', icon: '' }
            - { label: 'Les Produits' }
            - { entity: 'ProductType', label: 'Type de produit' , icon: '' }
            - { entity: 'Product', label: 'Produits', icon: '' }
            - { entity: 'Gender', label: 'Genre', icon: '' }
            - { entity: 'Size', label: 'Tailles' , icon: '' }
            - { entity: 'Logo', label: 'Logos' , icon: ''}
            - { entity: 'Color', label: 'Couleurs' , icon: ''}
            - { entity: 'StockInput', label: 'Stock' , icon: ''}
            - { label: 'Les Utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs' , icon: ''}
            - { entity: 'Address', label: 'Adresses' , icon: '' }
            - { label: 'Boutique' }
            - { label: '< Accéder au site', route: 'home' , icon: '' }
   entities:
       # List the entity class name you want to manage
       - App\Entity\Address
       - App\Entity\Color
       - App\Entity\Gender
       - App\Entity\Logo
       - App\Entity\Orders
       - App\Entity\OrderLine
       - App\Entity\Product
       - App\Entity\ProductType
       - App\Entity\Rate
       - App\Entity\Size
       - App\Entity\StockInput
       - App\Entity\User
