easy_admin:
   site_name: '<strong>Dev</strong> <em>my shirts</em>'
   formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
   list:
        actions: # renommage des boutons sur la section liste
            - { name: 'edit', label: 'Modifier' , icon: 'edit'}
            - { name: 'delete', label: 'Supprimer' , icon: 'trash'}
            - { name: 'new', label: 'Ajouter', icon: 'plus' }
            - { name: 'search', label: 'Rechercher' }
   edit: # boutton desactivé sur toutes les sections
        actions: ['-delete']
   new: # boutton desactivé sur toutes les sections
        actions: ['-delete']
   design:
        assets:
            favicon: 'assets/icone/favico.png'
            css:
                - 'https://use.fontawesome.com/releases/v5.6.1/css/all.css'
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'assets/style/admin.min.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
                - 'assets/script/admin.js'
        brand_color: '#084562'
        menu:
            - { label: 'Les Utilisateurs' }
            - { entity: 'Address', label: 'Adresses' , icon: 'map-marker-alt' }
            - { entity: 'Color', label: 'Couleurs' , icon: 'palette'}
            - { entity: 'Gender', label: 'Genres', icon: 'user' }
            - { entity: 'Logo', label: 'Logos' , icon: 'code'}
        # menu: 
        #     - { label: 'Les commandes' }
        #     - { entity: 'Orders', label: 'Numéro de commandes', icon: '', default: true }
        #     - { entity: 'OrderLine' , label: 'Détails Commandes' , icon: '' }
        #     - { entity: 'Rate', label: 'Remise', icon: '' }
        #     - { label: 'Les Produits' }
        #     - { entity: 'ProductType', label: 'Type de produit' , icon: '' }
        #     - { entity: 'Product', label: 'Produits', icon: '' }
        #     - { entity: 'Gender', label: 'Genre', icon: '' }
        #     - { entity: 'Size', label: 'Tailles' , icon: '' }
        #     - { entity: 'Logo', label: 'Logos' , icon: ''}
        #     - { entity: 'Color', label: 'Couleurs' , icon: ''}
        #     - { entity: 'StockInput', label: 'Stock' , icon: ''}
        #     - { label: 'Les Utilisateurs' }
        #     - { entity: 'User', label: 'Utilisateurs' , icon: ''}
        #     - { entity: 'Address', label: 'Adresses' , icon: '' }
        #     - { label: 'Boutique' }
        #     - { label: '< Accéder au site', route: 'home' , icon: '' }
   entities:
       # List the entity class name you want to manage
    #    - App\Entity\Address
    #    - App\Entity\Color
    #    - App\Entity\Gender
    #    - App\Entity\Logo
    #    - App\Entity\Orders
    #    - App\Entity\OrderLine
    #    - App\Entity\Product
    #    - App\Entity\ProductType
    #    - App\Entity\Rate
    #    - App\Entity\Size
    #    - App\Entity\StockInput
       Address: # Entité
            class: App\Entity\Address # chemin d'accés à l'entité
            label: 'Adresses' # Le nom affiché de l'entité
            list: # mode liste
                title: 'Liste des adresses' # titre de la section
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'addressType', label: 'Type' }
                    - { property: 'street', label: 'Adresse' }
                    - { property: 'zipCode', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
                    - { property: 'createdDate', label: 'Date de création' }
            edit: # affichage "Modifier"
                title: "Modifier l'adresse"  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'addressType', label: 'Type' }
                    - { property: 'street', label: 'Adresse' }
                    - { property: 'zipCode', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
            new: # affichage "Ajouter"
                title: 'Ajouter une nouvelle adresse'  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'addressType', label: 'Type' }
                    - { property: 'street', label: 'Adresse' }
                    - { property: 'zipCode', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'country', label: 'Pays' }
            search: # affichage "Rechercher"
                title: 'Résultat de la recherche'  # titre de la section
       Color: # Entité
            class: App\Entity\Color # chemin d'accés à l'entité
            label: 'Couleurs' # Le nom affiché de l'entité
            list: # mode liste
                title: 'Liste des couleurs' # titre de la section
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'colorName', label: 'Couleur' }
                    - { property: 'colorHexa', label: 'Code Hexadécimal' }
                    - { property: 'createdDate', label: 'Date de création' }
            edit: # affichage "Modifier"
                title: "Modifier la couleur"  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'colorName', label: 'Couleur' }
                    - { property: 'colorHexa', label: 'Code Hexadécimal' }
            new: # affichage "Ajouter"
                title: 'Ajouter une nouvelle couleur'  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'colorName', label: 'Couleur' }
                    - { property: 'colorHexa', label: 'Code Hexadécimal' }
            search: # affichage "Rechercher"
                title: 'Résultat de la recherche'  # titre de la section
       Gender: # Entité
            class: App\Entity\Gender # chemin d'accés à l'entité
            label: 'Genres' # Le nom affiché de l'entité
            list: # mode liste
                title: 'Liste des genres' # titre de la section
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'Name', label: 'Genre' }
                    - { property: 'createdDate', label: 'Date de création' }
            edit: # affichage "Modifier"
                title: "Modifier le genre"  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'Name', label: 'Genre' }
            new: # affichage "Ajouter"
                title: 'Ajouter un nouveau genre'  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'Name', label: 'Genre' }
            search: # affichage "Rechercher"
                title: 'Résultat de la recherche'  # titre de la section
       Logo: # Entité
            class: App\Entity\Logo # chemin d'accés à l'entité
            label: 'Logos' # Le nom affiché de l'entité
            list: # mode liste
                title: 'Liste des Logos' # titre de la section
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'logoName', label: 'Logo' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'createdDate', label: 'Date de création' }
            edit: # affichage "Modifier"
                title: "Modifier le logo"  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'logoName', label: 'Logo' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'link', label: 'Lien' }
            new: # affichage "Ajouter"
                title: 'Ajouter un logo'  # titre de la section
                actions: # les boutons à afficher
                    - { name: 'list', label: 'Retour', icon: 'arrow-left' }
                fields: # champas à afficher
                    - { property: 'id', label: 'ID' }
                    - { property: 'logoName', label: 'Logo' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'link', label: 'Lien' }
            search: # affichage "Rechercher"
                title: 'Résultat de la recherche'  # titre de la section

